allowHostPorts: true
priority: 1
requiredDropCapabilities: []
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
users:
  - 'system:serviceaccount:gatekeeper-system:gatekeeper-admin'
allowHostDirVolumePlugin: true
seccompProfiles:
  - '*'
allowHostIPC: true
seLinuxContext:
  type: RunAsAny
readOnlyRootFilesystem: false
metadata:
  generation: 2
  name: gatekeeper-scc
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
defaultAddCapabilities: []
allowedUnsafeSysctls:
  - '*'
supplementalGroups:
  type: RunAsAny
volumes:
  - '*'
allowHostPID: true
allowHostNetwork: true
allowPrivilegeEscalation: true
apiVersion: security.openshift.io/v1
allowedCapabilities:
  - '*'
